version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: openfga
      POSTGRES_PASSWORD: openfga
      POSTGRES_DB: openfga
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openfga"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: openfga/openfga:v1.5.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      OPENFGA_DATASTORE_ENGINE: "postgres"
      OPENFGA_DATASTORE_URI: "postgres://openfga:openfga@postgres:5432/openfga?sslmode=disable"
    command:
      - migrate
    restart: on-failure

  openfga:
    image: openfga/openfga:v1.5.0
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      OPENFGA_DATASTORE_ENGINE: "postgres"
      OPENFGA_DATASTORE_URI: "postgres://openfga:openfga@postgres:5432/openfga?sslmode=disable"
      OPENFGA_LOG_FORMAT: "json"
      OPENFGA_AUTHN_METHOD: "none"
    command:
      - run
      - --http-addr=0.0.0.0:8080
      - --grpc-addr=0.0.0.0:8081
    ports:
      - "8080:8080"
      - "8081:8081"
